<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>1 input_Ruas</name>
   <tag></tag>
   <elementGuidId>22d28058-9597-4a42-9366-d818706f4c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-8znh176fm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='mantine-Input-input mantine-TextInput-input mantine-9bu0gs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6ec2cf1-63e1-4862-b9bb-6a05fd83173a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Input-input mantine-TextInput-input mantine-9bu0gs</value>
      <webElementGuid>066703a6-0231-4649-9c9e-70a60afcd14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-8znh176fm</value>
      <webElementGuid>980c5b41-21f7-4134-af1b-eebed5f4371b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c7cca91-6a98-487c-a11e-e94cdd9a17fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cbaba73f-8cc6-49c6-88ab-ba38fce253d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-8znh176fm&quot;)</value>
      <webElementGuid>797c2d21-4708-4f00-bf47-8661661fb933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-8znh176fm']</value>
      <webElementGuid>0a3b9120-67d5-4661-842c-63bfae815786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-n9yf000gl-body']/div/form/div/div/div/div/input</value>
      <webElementGuid>c1a3608d-733d-4b23-9e84-ab2cdb25e521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>afa3001e-29a2-465c-aeb4-6d43cd01ce39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mantine-8znh176fm' and @type = 'text']</value>
      <webElementGuid>07dc2187-0d09-45a2-ab37-09e6ebb3504c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
