<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2 input_Unit Kerja</name>
   <tag></tag>
   <elementGuidId>dc5bb0c2-9439-4849-9aea-29ee8aadc0b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-j58jwpnkh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='mantine-Input-input mantine-Select-input mantine-1rr4qfu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69594deb-ad73-41fc-b4a9-34fc31787558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Input-input mantine-Select-input mantine-1rr4qfu</value>
      <webElementGuid>ce92dbce-9ff6-4a2d-b934-5ecad853d562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>27fd4d9f-3243-4d15-ac51-2461475cdcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>5b4885d4-f1d4-46fa-a240-68d2c7be075b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-j58jwpnkh</value>
      <webElementGuid>df667f08-86b5-4a4d-b0fe-d785526b0edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Unit Kerja</value>
      <webElementGuid>f6327355-6754-42fc-80b0-1d5e4403552d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>bac8c1f8-2aee-4fe9-ad6c-d8778864064c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mantine-stop-propagation</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a7bc84fc-1538-484c-8ac2-b36fb3711325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>85beaa70-7b66-40ef-86ba-be3416656df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-j58jwpnkh&quot;)</value>
      <webElementGuid>f0070ffa-5345-4cbb-aebf-abac463f291b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-j58jwpnkh']</value>
      <webElementGuid>22ed10d9-ff2e-4090-8a09-a4a8a5e3cc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-n9yf000gl-body']/div/form/div/div/div[3]/div/div/input</value>
      <webElementGuid>16ddb036-826c-4a6e-bf73-e3a5f9d2218f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>4e2bb196-968c-43ae-8b1c-4fc5116fce4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'mantine-j58jwpnkh' and @placeholder = 'Pilih Unit Kerja']</value>
      <webElementGuid>451bfc06-fc63-420e-99f1-3383d3aab9cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
