<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3 input_Panjang (km)</name>
   <tag></tag>
   <elementGuidId>2c5d47a1-0a0b-4304-a7bd-63717ec87894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#long</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='long']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ef82c52-b3d7-42da-9f20-9bc59fe92c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Input-input mantine-9bu0gs</value>
      <webElementGuid>f260807e-a23d-4ac0-a21f-7d1b16d788dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>long</value>
      <webElementGuid>ce6281f1-d239-4a7d-a896-e209b28443cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ec799324-f3a4-4dc4-b340-a38043a661dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5a72159-795c-4f73-b6e7-081382826101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;long&quot;)</value>
      <webElementGuid>f524f1e4-0b7c-4518-b1ee-6331fdd6a78d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='long']</value>
      <webElementGuid>4d1b29bc-22a8-494d-8084-dffd4856a0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-n9yf000gl-body']/div/form/div/div/div[4]/div/input</value>
      <webElementGuid>6a2315ee-95cc-49d3-91b6-376fb7958bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>105fd0a9-e811-41a5-9326-a76f09b54381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'long' and @type = 'number']</value>
      <webElementGuid>82f7a345-16d4-485e-9046-3e96c0bb0afc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
