<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>77c601f4-b70a-4a1d-b435-943f3f2c4195</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mantine-UnstyledButton-root.mantine-Button-root.mantine-qb3hms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f8f9184-8d24-45b8-8dde-dc43a90c14d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-UnstyledButton-root mantine-Button-root mantine-qb3hms</value>
      <webElementGuid>ce3c0f34-a783-4131-979d-6e6023ba5cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>97b4d833-a38a-4a6b-9477-9eab53ceb401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b174d66d-db34-48c8-bf5e-b0826b14b34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>7f34e2ed-4280-4bdc-88db-72f4ad460f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-n9yf000gl-body&quot;)/div[@class=&quot;mantine-1avyp1d&quot;]/form[1]/div[@class=&quot;mantine-hqlwd4&quot;]/button[@class=&quot;mantine-UnstyledButton-root mantine-Button-root mantine-qb3hms&quot;]</value>
      <webElementGuid>b2ef7c8d-19ea-490d-a502-e165ff7aec7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>01b23328-ee4b-4373-9f6f-e5e88ce16c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-n9yf000gl-body']/div/form/div[8]/button[2]</value>
      <webElementGuid>7cd789f1-2ee3-4573-b808-b795381a771f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/following::button[1]</value>
      <webElementGuid>8180afe4-23a0-4cf0-80df-ca948cfc714a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Ruas'])[2]/following::button[2]</value>
      <webElementGuid>11e89677-cc85-4cfa-9efe-199f5869598e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/button[2]</value>
      <webElementGuid>d22798fe-044e-4d1a-9f22-b8830bf11d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>dd5bb944-d446-4a62-a875-e0e93923c225</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
