<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__profile</name>
   <tag></tag>
   <elementGuidId>2ea54ada-6155-4b92-850e-0e0e9390fbbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-8ua8f4zeq-target</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class=&quot;mantine-UnstyledButton-root mantine-ActionIcon-root mantine-1otbv59&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b32b9a12-1696-4a17-a6e2-c7f950d61fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-UnstyledButton-root mantine-ActionIcon-root mantine-1otbv59</value>
      <webElementGuid>6b56dddd-9169-4491-93b9-c7968d873b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55317b1f-7109-4ac1-8335-586dbe2c0c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>b7d38850-d9e3-4ad2-b8d9-bf8aa0013d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>81afe2f2-e0de-4c93-bf65-23fc0b29eb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>mantine-8ua8f4zeq-dropdown</value>
      <webElementGuid>6e2229b5-b3b9-4c1b-89c6-2a62de3ef46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-8ua8f4zeq-target</value>
      <webElementGuid>7734aeb4-9562-4062-98a4-72a8966f8864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-8ua8f4zeq-target&quot;)</value>
      <webElementGuid>c5c77366-b1e2-4db4-8eab-92f774f6a669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mantine-8ua8f4zeq-target']</value>
      <webElementGuid>4a0de725-4932-4f0f-9242-54a8a3fd8917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div/div[3]/button</value>
      <webElementGuid>06902a9b-717c-48b0-a113-969ee2d62d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/preceding::button[5]</value>
      <webElementGuid>26ae0e60-2e9a-4367-b619-d9e846ad4d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1ede7d1b-1ae0-4dca-b2e3-9c6dc9d8bd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'mantine-8ua8f4zeq-target']</value>
      <webElementGuid>dfc2894b-e50d-4dbe-8e5e-a83097663706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
