<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_JIMMS</name>
   <tag></tag>
   <elementGuidId>9422a7e2-ddcc-4b66-84b3-6f011b605e25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;JIMMS Logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/header/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>24b786df-ee16-48b3-901e-0abc8991587d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>JIMMS Logo</value>
      <webElementGuid>42cc5113-b36d-4351-a211-4e384422083c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>164</value>
      <webElementGuid>138bdee2-e9aa-4f46-a5e7-910b5c30305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>8a7f7329-af62-403b-912e-ba4a977ae211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>0ec8a975-0e4a-44c0-9bc2-bccde0fd2298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>472af2fe-1c0b-4662-8bf2-fd52f3ed3d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fjimms_logo_transparent.png&amp;w=256&amp;q=75 1x, /_next/image?url=%2Fjimms_logo_transparent.png&amp;w=384&amp;q=75 2x</value>
      <webElementGuid>2d21e658-c675-46b3-9311-0cd0ab05928c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fjimms_logo_transparent.png&amp;w=384&amp;q=75</value>
      <webElementGuid>32aed9a2-1715-4a9a-8b6e-6dee214461e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;mantine-1avyp1d&quot;]/header[@class=&quot;mantine-Header-root mantine-11i5pqo&quot;]/div[@class=&quot;mantine-Group-root mantine-1vdqnc0&quot;]/div[@class=&quot;mantine-15bevxs&quot;]/a[1]/img[1]</value>
      <webElementGuid>5c13c966-f1fd-439a-9c3a-a6e575575d55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div/div/a/img</value>
      <webElementGuid>713e0b95-bd86-490e-8cc2-2eedce3f667c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='JIMMS Logo']</value>
      <webElementGuid>48a91681-7a4f-41ed-ab4e-3846de538cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>97f70c5d-2097-4f54-adc4-647a7fff4bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'JIMMS Logo' and @src = '/_next/image?url=%2Fjimms_logo_transparent.png&amp;w=384&amp;q=75']</value>
      <webElementGuid>4896f6da-8904-4c44-bab3-0f6abe8959c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
