<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ruas</name>
   <tag></tag>
   <elementGuidId>fd72de2f-bcb4-4293-9b3e-37f03eb38107</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.mantine-UnstyledButton-root.mantine-NavLink-root.mantine-fp63oe > span.mantine-dstkpx.mantine-NavLink-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;mantine-1umouvl mantine-NavLink-children&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>788bd305-3541-4258-8924-dd889f142b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-dstkpx mantine-NavLink-body</value>
      <webElementGuid>d8e5e474-69a9-489b-962f-b5e5319d5b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ruas</value>
      <webElementGuid>76065a67-3404-4bed-beb7-8564d67ab4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-4vlq1abi9-dropdown&quot;)/div[1]/div[@class=&quot;mantine-1avyp1d&quot;]/div[1]/div[@class=&quot;mantine-1umouvl mantine-NavLink-children&quot;]/div[@class=&quot;mantine-ScrollArea-root mantine-mohg2k&quot;]/div[@class=&quot;mantine-b6zkvl mantine-ScrollArea-viewport&quot;]/div[1]/a[1]/button[@class=&quot;mantine-UnstyledButton-root mantine-NavLink-root mantine-fp63oe&quot;]/span[@class=&quot;mantine-dstkpx mantine-NavLink-body&quot;]</value>
      <webElementGuid>a7064cee-642c-47cf-8208-e39682a86376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-4vlq1abi9-dropdown']/div/div[2]/div/div/div/div/div/a/button/span[2]</value>
      <webElementGuid>e269b6ff-9ef4-4bb5-8855-0766186e659c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[1]/following::span[4]</value>
      <webElementGuid>adbf19a6-c09d-4db0-a4b4-9657b5980e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator'])[1]/following::span[7]</value>
      <webElementGuid>9e997cc6-daa0-4c09-b19f-32ab5b0e739c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button/span[2]</value>
      <webElementGuid>177f12da-de95-4861-8fe1-ed5baa12ac1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Ruas' or . = 'Ruas')]</value>
      <webElementGuid>73539867-4520-48c0-8a37-b4ee298b2f09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
